### ISSUE TITLE
onnect it with the mrz realpass reader

### ISSUE THREAD

**Issue by jehadfeesh** [paucapo/mrz-reader#1]
Hi dear
Is this script able to connect it with the mrz realpass reader?
whatsapp 00970595533995
jehadfeesh@gmail.com
fb : www.fb.com/jehadfeesh
plz contact me

**Comment by paucapo** [comment]
I'm sorry but I don't know what is MRZ Realpass Reader and I don't have in mind to do any work integrating this script with any other program.

**Comment by jehadfeesh** [comment]
Thank you for your prompt reply
Please explain how to connect a scanner or camera to this script

**Comment by paucapo** [comment]
Check-out the demo directory, the webcam.html file is a sample using a camera. The scanners are not supported.
